### PR TITLE
Include PlayStation 2 changes for newlib library & rebase

### PR DESCRIPTION
**Pull request by fjtrujy**
## Description
This PR contains 2 main features:

- Remove some specific code for `_EE` no longer needed after include `newlib`

- Rebase and includes the PS2 changes onto `Master` branch.  As you know previously it was as a separate branch called `ps2` and it was kind of outdated comparing with the current `Master` from the original repo.

Anyway if you don't want merge directly to `Master` we can create a separate `PS2-master` branch.

Thanks!

### CODE REVIEW

**Comment by fjtrujy** [comment]
By the way, please, don't remove the original `PS2` branch from now. 
Thanks again

**Comment by mlafeldt** [comment]
@fjtrujy Could you please open that PR against the PS2 branch, which is meant to contain the PS2-specific changes?

**Comment by fjtrujy** [comment]
The problem about the PS2 branch is that is quite outdated. 
And I would like to have the PS2 changes onto Master, and not mixed, which is making more difficult to identify PS2 specific changes.

If you want, you can create another PS2 branch called for instance `ps2-newlib` I can change the target branch to this new branch.

What do you think?

**Comment by rickgaiser** [comment]
The changes are not really newlib related, so perhaps another branch name than ps2-newlib. It's more of a rebase to the latest upstream changes. So perhaps ps2-v2 or ps2-2020 would be more appropriate?

If a new branch is not wanted the changes can also be merged into the ps2 branch.

**Comment by fjtrujy** [comment]
Yeah, you're totally right @rickgaiser !
Thanks

**Comment by fjtrujy** [comment]
Closing this PR because it is going to be included directly in ps2dev group.
Thanks!

**Pull request closed without merging**
